### ISSUE TITLE
Regression on multiple files

### ISSUE THREAD

**Issue by wd5gnr** [arhefner/Asm-02#11]
I'm not sure if this was from my PR or your changes to the PR but there is a regression when assembling multiple files.

At the start clear() is called and then the code tries to addlabel() for the fixed labels like R0, R1, etc. This causes a segfault. It looks like the label storage gets freed and then realloc'd. I will chase it down shortly.

**Comment by wd5gnr** [comment]
Oddy it is intermittent and I'm trying to figure out what is the trigger.  But it is definitely in the addLabel for R0 on a second file from the command line.

**Comment by wd5gnr** [comment]
So the difference is in a different version of kernel.inc. The "bad" one has the newer kernel defines but it doesn't look bad in any way and it does assemble ok on the first file, just not the second. But the good one assembles all the time. Very strange.

**Comment by wd5gnr** [comment]
Ok I got it.  There are two places all the label arrays are cleared and one of them did not sufficiently wipe out the pointers. I pulled the code out and called it from both places although it isn't clear to me that it needs to be called from both places. I'll push a PR in a second.

**Comment by arhefner** [comment]
PR merged.
