### ISSUE TITLE
Data field in a relocatable file received *ERROR: Memory overwrite at address 0000

### ISSUE THREAD

**Issue by fourstix** [arhefner/Asm-02#8]
I have a library that has a data field in a relocatable module. The Assembler assigns the field's address as 0 in the .prg file and later the linker will supply the actual address.

When I assembled the lcd_send_cmd.asm file with the following command:
C:\Asm02\asm02 -L -D1802MINIPLUS lcd_send_cmd.asm

I received the following output:
C:\Elfos-I2C\lcd>C:\Users\fours\Utilities\Asm02\asm02 -L -D1802MINIPLUS lcd_send_cmd.asm
Asm/02 v1.7
by Michael H. Riley
lcd_send_cmd.asm:91: *ERROR: Memory overwrite at address 0000
   91 |             db LCD_CMD          ; default command bits (RS off, Backlight on)

Lines Assembled   : 735
Code Generated    : 65
Errors            : 1

This should not be flagged as an error since the code is relocatable and this data field will not over-lap any existing address.

The source file lcd_send_cmd.asm is attached with the txt extension added.
[lcd_send_cmd.asm.txt](https://github.com/arhefner/Asm-02/files/12569435/lcd_send_cmd.asm.txt)

**Comment by fourstix** [comment]
I submitted Pull Request #9 to fix this issue.

**Comment by wd5gnr** [comment]
My original implementation only checked overlap in I and B mode, so yes agree this should not be on for R.

**Comment by arhefner** [comment]
It is true that overwrite errors should not occur in relocatable blocks (proc/endp). The code attempted to make that true, but there was an error in the implementation. It is possible to place code at specific addresses with org even when the assembler is operating in relocatable mode and the linker will respect the absolute placement, so I don't want to blanket turn off the error checking when the assembler is in this mode. I put in a fix for the problem, so I'm closing this issue and the pull request.
